### ISSUE TITLE
Update QI Qiskit SDK for upstream Qiskit

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/quantuminspire#108]
# Bug report

The Qiskit SDK uses the `from qiskit.providers import BaseBackend` class which has been deprecated. The Qiskit SDK should be updated to use the modern qiskit `Backend`.

https://github.com/QuTech-Delft/quantuminspire/blob/dev/src/quantuminspire/qiskit/backend_qx.py#L40

@oschusler @QFer

**Comment by QFer** [comment]
@peendebak We can combine this with updating BaseJob we use for QIJob which is also deprecated.
Instead we should use `qiskit.providers.JobV1`

**Comment by QFer** [comment]
Solved by https://github.com/QuTech-Delft/quantuminspire/pull/116
