### ISSUE TITLE
Use plain dict instead of OrderedDict in the QI SDK

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/quantuminspire#111]
Since Python 3.6 the `dict` is ordered. There is no reason to use the `OrderedDict` in the QI SDK. Using the normal `dict` has the advantage that is is better in displaying the results and that the result structures are easier to serialize.

@QFer

**Comment by QFer** [comment]
@peendebak

Solved by https://github.com/QuTech-Delft/quantuminspire/pull/115
