### ISSUE TITLE
Method to_dict() on QI Qiskit Result cannot be serialized

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/quantuminspire#132]
After execution of a job with the QI Qiskit backend there is a `qiskit.result.Result` object. Calling the method `to_dict()` results in a dictionary with the status field set to an object which prevents the dict from being serialized

![image](https://user-images.githubusercontent.com/17724047/152407754-faafcc18-84cb-41a6-b28a-216675f38295.png)

The normal qiskit backends create a dict with the status field set to a string.

@QFer

**Comment by QFer** [comment]
Fix is merged to dev
