### ISSUE TITLE
Unexpected answers when using multiple classical registers. 

### ISSUE THREAD

**Issue by nielsneumann** [QuTech-Delft/quantuminspire#134]
# Bug report
We tried to implement an algorithm with one quantum register and multiple classical registers. We get unexpected answers and outcomes that should not even occur. When replacing the two classical registers by a single one, the problem is solved. 

## What did you try to do?
In our example, we implemented a Toffoli gate, using a GHZ-state. Below the code we used. 

`import qiskit
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, Aer

import quantuminspire
from quantuminspire.qiskit import QI
import os

server_url = r'https://api.quantum-inspire.com'
token = quantuminspire.credentials.load_account()
project_name = 'distributed-dbc'
qi_authentication = quantuminspire.credentials.get_token_authentication(token)

QI_URL = os.getenv("API_URL", "https://api.quantum-inspire.com/")
QI.set_authentication(qi_authentication, QI_URL, project_name=project_name)

def measure_circuit(qc, backend='QuantumInspire'):
    if backend == 'QuantumInspire':
        backend = QI.get_backend('QX single-node simulator')
    else:
        backend = Aer.get_backend("qasm_simulator")
    result = qiskit.execute(experiments=qc, backend=backend, shots=1024).result()
    return result.get_counts()

qr = QuantumRegister(5)
cr = ClassicalRegister(3)
cr_ghz = ClassicalRegister(2)
circuit = QuantumCircuit(qr, cr, cr_ghz)

circuit.x(1)
circuit.h(0)
circuit.h(2)
circuit.cx(2, 3)
circuit.ccx(0,1,2)
circuit.measure(2, cr_ghz[0])
circuit.x(2).c_if(cr_ghz[0], 1)
circuit.x(3).c_if(cr_ghz[0], 1)
circuit.cx(3,4)
circuit.h(3)
circuit.measure(3, cr_ghz[1])
circuit.cz(0,1).c_if(cr_ghz[1], 1)
circuit.x(3).c_if(cr_ghz[1], 1)

circuit.measure([0,1,4], cr)
circuit.measure([2,3], cr_ghz)

measure_QI = measure_circuit(circuit, backend="QuantumInspire")
measure_Qiskit = measure_circuit(circuit, backend="qasm_simulator")

print(measure_QI)
print(measure_Qiskit)`

When running this circuit on Qiskit, we obtain the states 00 010 and 00 111 with roughly fifty-fifty probability. A QI run however gives as results
{'00 010': 131, '00 111': 128, '01 011': 113, '01 110': 122, '10 010': 130, '10 111': 129, '11 011': 131, '11 110': 140}
This result is unexpected, also because states occur which should not even arise, e.g. 111 or 010. Furthermore, the first two qubits should be in the zero-state, however, this is also not always the case.

**Comment by QFer** [comment]
In cQasm measurement of a qubit is always stored to a classical bit with the same index.
The qiskit backend however, is able to handle measurement of qubits to classical bits with a different index. We keep track of the mapping between these qubits and classical bits. That's why this algorithm should work. The problem is that in handling the conditionals the mapping is not used correctly. A fix will be created soon.
