### ISSUE TITLE
Support the SX gate

### ISSUE THREAD

**Issue by eendebakpt** [QuTech-Delft/quantuminspire#148]
**Is your feature request related to a problem? Please describe.**

The [SX gate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.SXGate.html) is a common gate used in experiments. 
It should be supported by all QI backends as it can be readily transformed into an RX(pi/2) and a phase gate.

**Describe the solution you'd like**

The SX gate supported from the qiskit interface.

**Comment by eendebakpt** [comment]
> @eendebakpt Is this a valid issue for quantuminspire SDK? When the sx-gate is used in an algorithm and the quantum inspire backend doesn't support it, it is already transformed to the supported rx-gate isn't it? For example when we define the following algorithm for one of our simulators:
> 
> ```
> q = QuantumRegister(5)
> b = ClassicalRegister(5)
> circuit = QuantumCircuit(q, b)
> circuit.sx(q[4])
> qi_job = execute(circuit, backend=qi_backend, shots=256)
> ```
> 
> the following cQasm is sent to the simulator:
> 
> ```
> version 1.0
> # cQASM generated by QI backend for Qiskit
> qubits 5
> Rx q[4], 1.570796
> ```

The following example still fails:
```
backend='Starmon-5'
QI.set_authentication(authentication, QI_URL)
qi_backend = QI.get_backend(backend)

circuit = QuantumCircuit(2, name='Test')
circuit.h(0)
circuit.cx(0, 1)
circuit.s(0)
circuit.sx(0)

circuit.measure_all()
qi_backend.run(circuit)
```

**Comment by QFer** [comment]
By calling run on the backend directly you miss the transpiler step from Qiskit which tries to decompose the sx-gate to gates that are supported on the backend.

Instead of:
qi_backend.run(circuit)
do:
qi_job = execute(circuit, backend=qi_backend, shots=1024)
