### ISSUE TITLE
Make the project name from the SDK configurable

### ISSUE THREAD

**Issue by eendebakpt** [QuTech-Delft/quantuminspire#151]
The project name from the SDK is hardcoded (with a uuid), see https://github.com/QuTech-Delft/quantuminspire/blob/dev/src/quantuminspire/qiskit/backend_qx.py#L182

Can we make the project name configurable? Either as an attribute of the backend instance, or a runtime argument to `backend.run`?

**Comment by QFer** [comment]
There are a few ways to set the project name as described in readme.md paragraph **Configure a project name for Quantum Inspire**. The hard coded project name is used in case the project name is not set.
