### ISSUE TITLE
QI backend does not support QISKIT aqua VQE

### ISSUE THREAD

**Issue by kel85uk** [QuTech-Delft/quantuminspire#51]
# Bug report
## What did you try to do?

Tried to use the VQE solver from QISKIT Aqua with the QI backend. Tried to run notebook. Please rename extension from log to just .ipynb
[QI_sdk_qiskit_error.ipynb.log](https://github.com/QuTech-Delft/quantuminspire/files/3141611/QI_sdk_qiskit_error.ipynb.log)

## What did you expect to happen?
Provide no errors when running the notebook.

## What actually happened?
Please see the error in the notebook

## Environment

Please specify:
Ubuntu 18.04
Python 3.7.1 (Anaconda)
List of packages: See the log file
[packages.log](https://github.com/QuTech-Delft/quantuminspire/files/3141608/packages.log)

**Comment by quantumkoen** [comment]
Hi, thanks for the bugreport! I've created a ticket on our internal backlog to have a look at this issue, it will be scheduled for our upcoming sprint which starts this monday.

**Comment by QFer** [comment]
Created pull request #54 for the fix. I fixed it for the latest version of qiskit (0.10.1) with the latest version of qiskit-terra/qiskit-aqua. I had to change some minor things in the notebook to make it work for this new version of qiskit. I'll attach the changed notebook. After releasing the new SDK, which is compatible with qiskit >= 0.9.0, the notebook runs.

Please be aware that with SPSA(max_trials=300) can take hours to run on Quantum Inspire backend!!

[QI_sdk_qiskit_error.ipynb.log](https://github.com/QuTech-Delft/quantuminspire/files/3190840/QI_sdk_qiskit_error.ipynb.log)
