### ISSUE TITLE
QuantumInspireBackend.configuration() : n_qubits vs 'number_of_qubits"

### ISSUE THREAD

**Issue by jwoehr** [QuTech-Delft/quantuminspire#82]
# Feature request
Please clarify usage of `QuantumInspireBackend.configuration().n_qubits` vs  `QuantumInspireBackend.configuration()['_QuantumInspireBackend__backend']['number_of_qubits']`
## User story
In Qiskit for IBM Q devices, the pattern is:
```
large_enough_devices = self.provider.backends(
                    filters=lambda x: x.configuration().n_qubits >= self.num_qubits)
```
However in QI Qiskit, `x.configuration().n_qubits` returns a fixed number, for the backends I have access to, always `26`, whereas `x.configuration()['_QuantumInspireBackend__backend']['number_of_qubits']` returns the device's actual available number of qubits.

Can you please clarify usage?

## Acceptance criteria

Clear statement of the intended programming semantic.

## Environment
All relevant client platforms.

**Comment by QFer** [comment]
Hi Jack J. Woehr,

Currently we do not make full use of the backend information available. We have picked up this issue. I will inform you here when we merged a solution for this to the dev-branch.

**Comment by jwoehr** [comment]
@QFer thank you. For now, I have modified my code to use the information available in the dictionary, and it works.

**Comment by QFer** [comment]
@jwoehr Hi Jack,
Sorry that I didn't let you know earlier but the latest version of QuantumInspire does contain this functionality.

The default configuration is now adjusted for the specific backend you select. So the results for QuantumInspireBackend.configuration() now return what you expect. For example when choosing Starmon-5 as a backend the configuration will contain the values:
```
 backend_name = {str} 'Starmon-5'
 backend_version = {str} '1.3.0'
 basis_gates = {list} <class 'list'>: ['rx', 'ry', 'rz', 'x', 'y', 'h', 't', 's', 'tdg', 'sdg', 'id', 'z', 'cz', 'cx', 'swap', 'u1', 'u2', 'u3']
 conditional = {bool} False
 coupling_map = {list} <class 'list'>: [(0, 2), (1, 2), (2, 0), (2, 1), (2, 3), (2, 4), (3, 2), (4, 2)]
 gates = {list} <class 'list'>: [GateConfig(NotUsed, ['NaN'], NaN)]
 local = {bool} False
 max_experiments = {int} 3
 max_shots = {int} 16384
 memory = {bool} True
 n_qubits = {int} 5
 num_qubits = {int} 5
 open_pulse = {bool} False
 simulator = {bool} False
```
